### ISSUE TITLE
not handling disconnects properly

### ISSUE THREAD

**Issue by phit** [jaredlll08/MCBot#23]
https://gist.github.com/phit/31feb41cd9d1ced92d620b5fd48ba005

Not sure whats going on, I guess discord is having issues? This is the second time I had to 
`kill -9 pid` the process, as it wasn't responding to ctrl C or sending sigterm.

I was running build 236, updated to 240 as I saw D4J was updated, not sure if that will fix it. Figured I'll make an issue anyway if it doesn't.

**Comment by tterrag1098** [comment]
The D4J update should fix this.
