### ISSUE TITLE
Some embed tricks are broken

### ISSUE THREAD

**Issue by liach** [jaredlll08/MCBot#28]
Example (In sponge discord): https://discordapp.com/channels/142425412096491520/401643018773463040/591169260684836869 (and a few messages above)

Dunno why, but the bot is reportin "incorrect number of arguments".

**Comment by Runemoro** [comment]
I also get this exception when trying `!clj (zipmap [1 2] [3 4])`. This normally works in Clojure.

**Comment by tterrag1098** [comment]
Fixed by https://github.com/tterrag1098/K9/commit/faeed04c74bf6ba3de3a9ddc03de3a399e270416
