### ISSUE TITLE
Search results by MCP and srg name differs

### ISSUE THREAD

**Issue by XakepSDK** [jaredlll08/MCBot#32]
Check this screenshot:
First command result does not include `TileEntity` class
Is this intended?
![puush-linux+(2019-07-11+at+01 59 16)](https://user-images.githubusercontent.com/4938483/61000619-5b3c5280-a34d-11e9-80b4-f9a9f5bfce28.png)

**Comment by tterrag1098** [comment]
It's a side-effect of how I store the data and the fact that I do not get inheritance data, so I have to make a best-guess at which class "owns" a given method. The different name types have slightly different lookup mechanics. Bringing them in line might be possible.
