### ISSUE TITLE
trick parameters starting with a numeric character that are not numbers error

### ISSUE THREAD

**Issue by lavirlifiliol** [jaredlll08/MCBot#36]
Input: ?trick echo 4D
Expected output: ("4D")
actual output: Error evaluating trick: Invalid number: 4D

**Comment by lavirlifiliol** [comment]
To be exact, it seems to be parameters that end in /[lLdDfF]/ and possibly a few others.

**Comment by tterrag1098** [comment]
An issue with the differences between java and clojure numeric literals. That will be tricky to solve, since I just call out to a library method atm.
