### ISSUE TITLE
Suggestion: add a !react command

### ISSUE THREAD

**Issue by Runemoro** [jaredlll08/MCBot#37]
Add a !react command that takes a message link and emoji name as a parameter, and adds the reaction to the message, then removes it after 30 seconds. During this time, the person who used the command can click the reaction and add theirs, allowing non-nitro users to react with any emoji from a server K9 is on.

**Comment by tterrag1098** [comment]
Emoji name is not unique, plus I'm not really sure I want to be adding features that exist only to "hack" nitro features.
