### ISSUE TITLE
Question: Mojang proguard obfuscation map

### ISSUE THREAD

**Issue by liach** [jaredlll08/MCBot#39]
Since 19w36a, Mojang has released proguard obfuscation map. The map allows for "private use" and disallows any distribution.

So two questions:
1. Is it legal for K9 to add a mojang mapping lookup feature?
2. If it is legal, will K9 have such a feature?

**Comment by tterrag1098** [comment]
I will be waiting for further clarifications on the license before I implement anything like this. But it would be possible, technically.

**Comment by zml2008** [comment]
With the changes to the license announced a while back and Sponge's switch official names, would it be possible to take a look at implementing this again? It'd be nice for all of us trying to re-orient ourselves in our remapped codebase :)

**Comment by tterrag1098** [comment]
I'm open to it, but lacking time to add new features right now. Implementation should be straightforward, the mappings system is entirely extensible, both mcp and yarn implement the same API.

**Comment by tterrag1098** [comment]
Implemented by #63
