### ISSUE TITLE
(Enhancement) require a "battle" on quote creation to not have so many awful quotes.

### ISSUE THREAD

**Issue by LumberWizard** [jaredlll08/MCBot#40]
![image](https://user-images.githubusercontent.com/5213262/64473700-acf93180-d172-11e9-8439-500fe42a9117.png)
On the battle side of things I'd maybe not allow whitenames or bluenames who haven't been on the server for at least six months to vote? There are also people like Redfire who vote randomly, they should be banned from voting in battles.

**Comment by tterrag1098** [comment]
None of this is really actionable and it's mostly just complaining about moderation specific to one server. I don't want to make quote creation a popularity contest, that's what battles are for already.
