### ISSUE TITLE
[Quote Battle] Keep the winning quote in chat while voting for death or save

### ISSUE THREAD

**Issue by raphydaphy** [jaredlll08/MCBot#41]
As the title says, it would be great if we could see the winning quote in chat and the amount of votes for/against while the voting for death or spare is still active. 

![quote battle](https://imgur.com/04mKiM5.png)

Perhaps where the arrow is it could say something like ... "against Quote #<winning quote> by x votes`. It would be nice to be able to see the quote which was deemed better than the one that lost and by how much.

**Comment by tterrag1098** [comment]
I guess, but I don't really see why it matters? Choosing to kill or spare should be objective, it's not in any way related to what the other quote was. Adding it here would just take up space and provide no useful information.

**Comment by raphydaphy** [comment]
i guess
