### ISSUE TITLE
tricks not showing thrown exceptions

### ISSUE THREAD

**Issue by lavirlifiliol** [jaredlll08/MCBot#44]
creating a trick like:
```!trick -at clj trickname (throw (Exception. "Hi"))```
will output: 
```Error evaluating trick: null```
whereas
```!clj (throw (Exception. "Hi"))```
will output the expected
```Could not process command: java.security.PrivilegedActionException: java.lang.Exception: Hi```

**Comment by tterrag1098** [comment]
Pretty sure this was fixed ages ago
