### ISSUE TITLE
Hidden strings trigger pings

### ISSUE THREAD

**Issue by ramidzkh** [jaredlll08/MCBot#46]
https://github.com/tterrag1098/K9/blob/master/src/main/java/com/tterrag/k9/commands/CommandCustomPing.java#L81
Looks like things like emoji and channel names trigger pings. It's very annoying when someone does `<:any_string_they_want:emote id>` since the Discord client renders the emoji but you get the ping

**Comment by haykam821** [comment]
This issue should be closed.

**Comment by ravenbuilder934** [comment]
I prefer this. I have a ping set up for `bolb`, with the intention that it would ping me if Curle or anyone else uses a :bolb: emoji.
