### ISSUE TITLE
Command names are ambiguous and confusing

### ISSUE THREAD

**Issue by Sollace** [jaredlll08/MCBot#48]
1. None of their names actually describe what they do. The bot just assumes everyone will immediately know that `!yc` means `!lookup_class`
2. Some of them have multiple meanings (i.e. `mcage` can be `m_cage` or `mc_age`)
3. Running `!help` command doesn't do what help commands normally do (That's put under `!commands` for some reason, which does what `!list` would normally do)
4. Relating to 1: running `!commands` does not provide any description of what any of the commands actually do.

Suggested changes:
`!commands` -> `help` (and add descriptions as per `!help [command]`

(keep originals as aliases)
`!yc` -> `!class`
`!ym` -> `!method`
`!yf` -> `!field`
`!yp` -> `!param`
`!clj` -> `!eval`
`!mcage` -> `!mc_age`
`!yv` -> `!yarn_version`
`!lmgtfy` (imgur?) -> `!google`

**Comment by tterrag1098** [comment]
I prefer to keep the names short - you'll be typing them often and it doesn't take long to learn what they mean. The intended flow is `!help` -> `!commands` -> `!help [command]` for people completely new, or just `!help [command]` if you want to know what a certain command does.

The yarn commands won't be renamed because there are also mcp commands.

LMGTFY is an established meme/acronym, and thus the name of the command.

**Comment by Sollace** [comment]
> The intended flow is !help -> !commands -> !help [command]

That is a _terrible_ workflow. You're asking people to jump back and forth between two different commands whilst the first one people are going to try is _never_ to be the right one.

It should be `!help` -> `!help [command]`, no middle step, and `!help` should at least provide a short description of what the command does, with `!help [command]` an optional step to get more details. So really it should only be one step: `!help` to access an overview of the bot's capabilities.

> The yarn commands won't be renamed because there are also mcp commands.

Mcp commands? Where? They'd _not documented_! I'm not asking you to rename them. That' why I specifically said:
> (keep originals as aliases)

And if you'd bothered to fix the problems with the workflow above, maybe I'd know about these mythical "mcp commands".

I'm asking for you to give us alternatives that don't suck, Even after several months of being in the server, I think I know maybe one or two of these commands, and I still have to often refer to the `!help -> [confusion] -> !commands -> [read list three times] -> [confusion] -> [randomly pick one] -> !help [command] -> [repeat N times]` to find a command I'm looking for.

Sometimes I _can't_ find the command I need, and only after I've given up and decided the bot probably doesn't have such a command (had been looking for a command that prints out current yarn/fabric/api versions, for example, when I made this PR and only stumbled upon it afterwards when going through all the commands to compile above suggestions) do I actually find the command _by accident_ whilst looking for a _different command_.

> LMGTFY is an established meme/acronym, and thus the name of the command.

The meaning is not clear when it's not displayed in full uppercase (or in the font that Discord servers use) (is that an L or an I?) and I shouldn't have to point out the fact that some people won't be familiar with that meme. On principle, a meme is not a good name for something you expect people to have to use.

These names are about as good as trying to write a Minecraft mod without deobfuscating the game. They are _horrible_. Annoying at best, borderline unuseable at worst.

You absolutely _need_ to change it. I don't care how, just fix it, otherwise I can't use it.
