### ISSUE TITLE
K9 spamming ping notifications in guild chats

### ISSUE THREAD

**Issue by LemmaEOF** [jaredlll08/MCBot#55]
![Capto_Capture 2020-08-19_09-54-26_PM](https://user-images.githubusercontent.com/6722691/90718338-92767600-e266-11ea-9a3d-831401b4bab8.png)

[Message link](https://ptb.discordapp.com/channels/507304429255393322/576536198823018498/745864777883975680)

For some reason, K9 started sending ping notifications seemingly matching the regex `/.*/` to guild channels in Fabric discord. We have no idea why or how it started doing this

**Comment by tterrag1098** [comment]
Because you have insane users that set up wildcard pings and I made a mistake that send the ping message to the originating channel instead of DM. Fixed in 47fba6e0ded61d45c47de3526e09f2667f7e71ee
