### ISSUE TITLE
[Suggestion] xkcd linking

### ISSUE THREAD

**Issue by ravenbuilder934** [jaredlll08/MCBot#61]
(Idea from BobbyTablesBot on Reddit.)

Suggestion: If a user ran `!xkcd 303`, K9 would post the link to [xkcd 303](https://xkcd.com/303/) in the chat (keeping the embed). Same if they ran `!xkcd Compiling` or `!xkcd compiling`.
No idea how hard this would be to implement, but it'd be really neat 😄

**Comment by tterrag1098** [comment]
Sounds like a good use for a trick :)
